version: "3.9"

services:
  app:
    build: .
    container_name: shitgram
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: shit-base
    environment:
      POSTGRES_USER: uebok
      POSTGRES_PASSWORD: shit
      POSTGRES_DB: huyaza
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
